# etl/grid_row_builders.py
def _make_master_row(
    regime_id: int,
    era_int: int,
    side_flag: int,
    sl_val: float,
    tp_val: float,
    total_pos: int,
    win_pos: int,
    balance: float,
    max_dd: float,
    regime_cfg: dict,
) -> dict:
    return {
        "balance": float(balance),
        "SL": float(sl_val),
        "TP": float(tp_val),
        "win_pos": int(win_pos),
        "total_pos": int(total_pos),
        "side": int(side_flag),
        "exit_window_h": int(regime_cfg.get("exit_window_h", 0)),
        "limit_order_expiry_h": int(regime_cfg.get("limit_order_expiry_h", 0)),
        "use_limit_entry": bool(regime_cfg.get("use_limit_entry", False)),
        "trade_window_interval": int(regime_cfg.get("trade_window_interval", 0)),
        "era_int": int(era_int),
        "regime_id": int(regime_id),
        "ma_int": int(regime_cfg.get("ma_int", 0)),
        "ma_reversion": bool(regime_cfg.get("ma_reversion", False)),
        "entry_lookback_units": int(regime_cfg.get("entry_lookback_units", 0)),
        "use_bbw": bool(regime_cfg.get("use_bbw", False)),
        "bbw_periods": int(regime_cfg.get("bbw_periods", 0)),
        "bbw_std": float(regime_cfg.get("bbw_std", 0.0)),
        "bbw_thresholds": int(regime_cfg.get("bbw_thresholds", 0)),
        "use_stochastic": bool(regime_cfg.get("use_stochastic", False)),
        "stoch_key": str(regime_cfg.get("stoch_key", "OFF")),
        "use_trailing_sl": bool(regime_cfg.get("use_trailing_sl", False)),
        "trailing_sl_pct": float(regime_cfg.get("trailing_sl_pct", 0.0)),
        "trailing_sl_interval": int(regime_cfg.get("trailing_sl_interval", 0)),
        "trailing_sl_stop_at_pos": bool(regime_cfg.get("trailing_sl_stop_at_pos", True)),
        "max_drawdown": float(max_dd),
    }